name: MyApp-Deploy

on:
  push:
    branches:
      - main
      - develop
    paths:
      - cicd-demo-app/**
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - develop
    paths:
      - cicd-demo-app/**

jobs:
  deploy-using-ssh:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy using ssh
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
          PROJECT_DIRECTORY: ~/Toy-Project/cicd-demo-app/hello-frontend
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          command="cd ${PROJECT_DIRECTORY} && \
                  git pull && \
                  killall -9 node 2>/dev/null || true && \
                  sudo npm install && npm install pm2@latest -g && \
                  pm2 start npm --name "node" -- start"
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} $command
